Repository prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG, pull requests merged in 2023-09, with the labels that each got.

#34 🎉 라우팅 연결하기(수정)
  package-lock.json
  src/app/(root)/(routes)/login/page.tsx
  src/app/(root)/(routes)/post/[postId]/page.tsx
  src/app/(root)/(routes)/post/new/page.tsx
  src/app/(root)/(routes)/register/page.tsx
  src/app/(root)/(routes)/search/[keyword]/page.tsx
  src/app/(root)/(routes)/user/edit/password/page.tsx
  src/app/(root)/(routes)/user/edit/profile/page.tsx
  src/app/(root)/(routes)/user/page.tsx
  src/config/paths.ts
  src/lib/axios.ts
Labels: feature

#27 🎉 이미지 업로드 용 컴포넌트 개발
  public/images/upload.png
  public/images/uploadImage.svg
  src/components/molcules/file-picker/index.scss
  src/components/molcules/file-picker/index.stories.tsx
  src/components/molcules/file-picker/index.tsx
  src/components/molcules/file-picker/useDragging.ts
  src/config/assets.ts
  src/hooks/useDragging.tsx
Labels: feature

#31 :tada: auth 로직 설정 및 provider 제공
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/test-login/page.tsx
  src/app/(root)/layout.tsx
  src/app/api/auth-user/route.ts
  src/app/api/login/route.ts
  src/app/api/logout/route.ts
  src/app/api/signup/route.ts
  src/config/constants.ts
  src/hooks/useCurrentUser.ts
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/useParam.ts
  src/hooks/useSignup.ts
  src/lib/axios.ts
  src/lib/contexts/authProvider.tsx
  src/services/auth/index.ts
  src/types/user/index.ts
Labels: feature

#33 🎉 아바타 컴포넌트 개발
  public/images/pccIImage.svg
  src/components/atoms/Avatar/index.scss
  src/components/atoms/Avatar/index.stories.tsx
  src/components/atoms/Avatar/index.tsx
  src/config/assets.ts
Labels: feature

#59 🎉 global font 적용
  package-lock.json
  src/app/(root)/layout.tsx
  src/components/atoms/ImageButton/imageButton.tsx
  src/components/atoms/ImageButton/index.scss
  src/components/atoms/ImageButton/index.stories.ts
  src/components/atoms/ImageButton/index.tsx
  src/constants/font.tsx
Labels: feature

#60 🎉 카드 컴포넌트 생성 (+ Text 컴포넌트)
  public/images/dislike.svg
  public/images/like.svg
  src/components/atoms/Avatar/index.stories.tsx
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/Card/Card.tsx
  src/components/atoms/Card/index.scss
  src/components/atoms/Card/index.stories.ts
  src/components/atoms/Card/index.ts
  src/components/molcules/ LikeDislikeCount/LikeDislikeCount.tsx
  src/components/molcules/ LikeDislikeCount/index.scss
  src/components/molcules/ LikeDislikeCount/index.stories.ts
  src/components/molcules/ LikeDislikeCount/index.ts
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/CardPostItem/index.scss
  src/components/organisms/CardPostItem/index.stories.ts
  src/components/organisms/CardPostItem/index.ts
  src/components/text/Text.tsx
  src/components/text/index.scss
  src/components/text/index.stories.ts
  src/components/text/index.ts
  src/config/assets.ts
  src/styles/color-themes.scss
  src/styles/reset.scss
  src/types/color/index.ts
Labels: feature

#64 :tada: scss에서 alias 설정
  .storybook/main.ts
  next.config.js
Labels: feature

#61 🎉 댓글 API 연동하기 (찐 최종)
  src/app/(root)/(routes)/post/[postId]/page.tsx
  src/app/api/post/[postId]/route.ts
  src/components/atoms/Avatar/index.tsx
  src/components/molcules/Comment/Comment.tsx
  src/components/molcules/Comment/index.scss
  src/components/molcules/Comment/index.stories.tsx
  src/components/molcules/Comment/index.tsx
  src/components/organisms/CommentList/CommentList.tsx
  src/components/organisms/CommentList/CommentListContainer.tsx
  src/components/organisms/CommentList/index.scss
  src/components/organisms/CommentList/index.stories.tsx
  src/components/organisms/CommentList/index.tsx
  src/services/post/index.ts
Labels: feature

#70 :tada: input 컴포넌트 작성
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/post/new/page.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Input/index.scss
  src/components/atoms/Input/index.stories.ts
  src/components/atoms/Input/index.tsx
  src/components/templates/NewPostPageTemplate/NewPostPageTemplate.tsx
  src/components/templates/NewPostPageTemplate/index.scss
  src/components/templates/NewPostPageTemplate/index.tsx
Labels: feature

#73 :tada: text editor 추가
  package.json
  pnpm-lock.yaml
  src/components/atoms/Quill/Quill.tsx
  src/components/atoms/Quill/index.scss
  src/components/atoms/Quill/index.stories.ts
  src/components/atoms/Quill/index.tsx
  src/components/atoms/Quill/quillModule.ts
Labels: feature

#85 🎉 이미지 업로드 컴포넌트 File -> base64로 변경
  src/components/molcules/file-picker/index.stories.tsx
  src/components/molcules/file-picker/index.tsx
  src/utils/FiletoBaseUrl.ts
Labels: feature

#79 🎉 그리드 템플릿 컴포넌트 생성
  next.config.js
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/(root)/(routes)/user/[userId]/page.tsx
  src/components/atoms/Card/Card.tsx
  src/components/atoms/Card/index.scss
  src/components/atoms/Card/index.stories.ts
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/CardPostItem/index.stories.ts
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/components/templates/CardGridTemplate/index.scss
  src/components/templates/CardGridTemplate/index.ts
  src/config/paths.ts
  src/styles/reset.scss
Labels: feature

#87 🎉 업로드 페이지 form, API
  .env.example
  pnpm-lock.yaml
  src/app/api/posts/create/route.ts
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Button/index.stories.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Input/index.scss
  src/components/atoms/Quill/Quill.tsx
  src/components/templates/NewPostPageTemplate/NewPostPageTemplate.tsx
  src/components/templates/NewPostPageTemplate/index.scss
  src/config/environments.ts
  src/hooks/useUploadForm.ts
  src/lib/contexts/authProvider.tsx
  src/services/post/index.ts
Labels: feature, 리뷰 요청, 긴급

#92 :tada: 이미지 업로드 로직 수정
  src/app/api/posts/create/route.ts
  src/components/molcules/file-picker/index.tsx
  src/components/templates/NewPostPageTemplate/NewPostPageTemplate.tsx
  src/hooks/useUploadForm.ts
  src/lib/axios.ts
  src/services/post/index.ts
Labels: feature, 리뷰 요청

#91 🎉 전체 게시글 불러오기 api 연결
  next.config.js
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/api/channel/[channelId]/route.ts
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/queries/channel/index.ts
  src/services/channel/index.ts
  src/types/post/index.ts
Labels: feature, 리뷰 요청

#95 🎉 검색 바 컴포넌트 구현
  package-lock.json
  public/images/searchIcon.svg
  src/components/atoms/SearchBar/SearchBar.tsx
  src/components/atoms/SearchBar/index.scss
  src/components/atoms/SearchBar/index.stories.tsx
  src/components/atoms/SearchBar/index.tsx
  src/config/assets.ts
Labels: feature, 리뷰 요청

#96 :tada: api 에러 공통 처리 추가 및 제안
  src/app/api/auth-user/route.ts
  src/app/api/login/route.ts
  src/app/api/logout/route.ts
  src/app/api/signup/route.ts
  src/hooks/useServerCookie.ts
  src/lib/axios.ts
Labels: feature, 리뷰 요청, 긴급

#97 🎉 로그인 회원가입 로직 연결
  src/components/organisms/LogInForm/LoginForm.tsx
  src/components/organisms/SignUpForm/SignUpForm.tsx
Labels: 리뷰 요청

#99 🎉 헤더 컴포넌트 구현
  public/images/arrowBottomIcon.svg
  public/images/notification.svg
  src/app/(root)/(routes)/user/page.tsx
  src/components/atoms/DarkModeButton/index.tsx
  src/components/atoms/ImageButton/index.scss
  src/components/atoms/ImageButton/index.stories.ts
  src/components/atoms/NotificationButton/NotificationButton.tsx
  src/components/atoms/NotificationButton/index.stories.tsx
  src/components/atoms/NotificationButton/index.tsx
  src/components/atoms/SearchBar/index.scss
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/molcules/ModalDropdownList/index.scss
  src/components/molcules/ModalDropdownList/index.stories.tsx
  src/components/molcules/ModalDropdownList/index.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/index.scss
  src/components/organisms/Header/index.stories.tsx
  src/components/organisms/Header/index.tsx
  src/config/assets.ts
  src/config/paths.ts
  src/lib/axios.ts
  src/styles/layout.scss
Labels: feature, 리뷰 요청

#98 🎉 메인 페이지 무한 스크롤 (훅 분리 완료)
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/api/posts/route.ts
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/components/templates/CardGridTemplate/index.scss
  src/config/constants.ts
  src/hooks/useInfiniteScroll.ts
  src/queries/channel/index.ts
  src/services/channel/index.ts
Labels: feature, 리뷰 요청

#82 🎉 이미지 모달 컴포넌트
  src/app/(root)/layout.tsx
  src/components/atoms/Card/Card.tsx
  src/components/atoms/ImageModal/ImageModal.tsx
  src/components/atoms/ImageModal/index.scss
  src/components/atoms/ImageModal/index.tsx
  src/components/atoms/ImageModal/useModal.ts
  src/components/atoms/Portal/Portal.tsx
  src/components/atoms/Portal/index.tsx
Labels: feature, 리뷰 요청

#103 헤더 컴포넌트 api 연결 완료
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/(root)/layout.tsx
  src/app/api/posts/route.ts
  src/components/atoms/Card/Card.tsx
  src/components/atoms/ImageModal/ImageModal.tsx
  src/components/atoms/ImageModal/index.scss
  src/components/atoms/ImageModal/index.tsx
  src/components/atoms/ImageModal/useModal.ts
  src/components/atoms/Portal/Portal.tsx
  src/components/atoms/Portal/index.tsx
  src/components/molcules/LikeDislikeCount/index.scss
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/organisms/CardPostItem/index.scss
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/index.scss
  src/components/organisms/NavBar/index.tsx
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/components/templates/CardGridTemplate/index.scss
  src/config/constants.ts
  src/config/environments.ts
  src/hooks/useCurrentUser.ts
  src/hooks/useInfiniteScroll.ts
  src/queries/channel/index.ts
  src/services/channel/index.ts
Labels: feature, 리뷰 요청

#90 🎉 좋아요,싫어요 비율 그래프
  package-lock.json
  package.json
  src/components/molcules/LikeDislikeCount/LikeDislikeCount.tsx
  src/components/organisms/LikeDIsLikeProgressBar/index.stories.tsx
  src/components/organisms/LikeDIsLikeProgressBar/index.tsx
Labels: feature, 리뷰 요청

#100 🎉 사이드바 컴포넌트 구현 완료
  public/images/mainLogo.svg
  src/app/api/posts/route.ts
  src/app/api/users/route.ts
  src/components/organisms/NavBar/NavBar.tsx
  src/components/organisms/NavBar/index.scss
  src/components/organisms/NavBar/index.stories.tsx
  src/config/assets.ts
  src/queries/users/index.ts
  src/services/user/index.ts
Labels: feature, 리뷰 요청

#107 :bug: actions에 env 적용
  .env.example
  .github/workflows/pull-request.yml
  pnpm-lock.yaml
  src/components/organisms/NavBar/index.tsx
  src/config/environments.ts
Labels: 긴급, bug

#109 :bug: axios url 수정
  src/app/api/auth-user/route.ts
  src/app/api/login/route.ts
  src/app/api/logout/route.ts
  src/app/api/posts/create/route.ts
  src/app/api/signup/route.ts
  src/app/api/users/route.ts
  src/lib/axios.ts
  src/lib/axiosSever.ts
Labels: 리뷰 요청, bug

#105 :tada: useEffect 추가 및 로그아웃 시 바로 헤더 변경(레이아웃 문제 미해결)
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/organisms/Header/Header.tsx
Labels: 작업 중

#114 :tada: 메인 레이아웃 수정 완료
  src/app/(root)/layout.tsx
  src/components/organisms/Header/index.scss
  src/components/organisms/NavBar/index.scss
  src/styles/layout.scss
Labels: 리뷰 요청

#113 🎉 1차 스프린트 변경사항 적용
  src/components/atoms/Input/index.scss
  src/components/atoms/Quill/Quill.tsx
  src/components/atoms/Quill/index.scss
  src/hooks/useUploadForm.ts
  src/lib/contexts/authProvider.tsx
Labels: feature, 리뷰 요청

#130 :bug: auth validation 수정
  src/app/api/login/route.ts
  src/app/api/logout/route.ts
  src/app/api/posts/create/route.ts
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/organisms/LogInForm/LoginForm.tsx
  src/hooks/useCurrentUser.ts
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/useServerCookie.ts
  src/hooks/useSignup.ts
  src/lib/contexts/authProvider.tsx
Labels: 리뷰 요청, 긴급, bug

#122 ✨ 다크모드 새로고침 로컬스토리지 유지
  package-lock.json
  src/components/atoms/DarkModeButton/index.tsx
  src/components/organisms/Header/Header.tsx
  src/hooks/useStorage.ts
Labels: 리뷰 요청, bug

#124 :tada: 로그인 여부에 따른 반응적 헤더 구현 및 페이지이동 제한 적용(기능 구현 완료)
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/organisms/Header/Header.tsx
Labels: feature, 리뷰 요청

#128 🎉 이미지 컴포넌트 리팩토링 + 포스트 디테일 페이지 레이아웃 수정..!
  package-lock.json
  package.json
  src/components/molcules/file-picker/index.scss
  src/components/molcules/file-picker/index.tsx
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/components/templates/PostDetailTemplate/index.scss
Labels: feature, 리뷰 요청

#132 :tada: toast 적용
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/test-login/page.tsx
  src/app/(root)/layout.tsx
  src/components/atoms/Toast/Toast.tsx
  src/components/atoms/Toast/index.scss
  src/components/atoms/Toast/index.tsx
  src/hooks/useCurrentUser.ts
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/useSignup.ts
  src/hooks/useUploadForm.ts
  src/lib/axios.ts
  src/lib/contexts/authProvider.tsx
Labels: feature, 리뷰 요청

#148 🎉 사이드바 스크롤 디자인 수정
  package-lock.json
  src/components/organisms/NavBar/index.scss
Labels: feature, 리뷰 요청

#147 Update page.tsx
  src/app/(root)/(routes)/post/[postId]/page.tsx
Labels: 긴급, bug

#150 ✨ 아바타 컴포넌트 텍스트 넘침처리
  src/components/atoms/Avatar/index.tsx
Labels: feature, 리뷰 요청

#151 :tada: header 리팩터링
  src/components/atoms/Text/Text.tsx
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/molcules/ModalDropdownList/index.scss
  src/components/molcules/ModalDropdownList/index.stories.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/index.scss
  src/components/organisms/NavBar/index.scss
  src/hooks/useCurrentUser.ts
Labels: feature, 리뷰 요청

#149 🎉 모달 컴포넌트 생성
  src/components/atoms/Card/Card.tsx
  src/components/atoms/ImageModal/ImageModal.tsx
  src/components/atoms/ImageModal/index.scss
  src/components/molcules/ModalLayout/ModalProvider.tsx
  src/components/molcules/ModalLayout/index.scss
  src/components/molcules/ModalLayout/index.ts
  src/hooks/useModal.ts
  src/styles/color-themes.scss
Labels: feature, 리뷰 요청

#163 :bug: auth와 hydrate에러 수정
  pnpm-lock.yaml
  src/app/(root)/layout.tsx
  src/app/api/signup/route.ts
  src/components/atoms/Toast/ToastContainer.tsx
  src/components/organisms/SignUpForm/SignUpForm.tsx
  src/hooks/useCurrentUser.ts
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/useSignup.ts
Labels: 리뷰 요청, 긴급, bug

#154 🎉 비밀번호 변경 페이지 컴포넌트화 및 비밀번호 변경 로직 연결
  package-lock.json
  public/images/backIcon.svg
  src/app/(root)/(routes)/user/edit/password/page.tsx
  src/app/api/users/edit/password/route.ts
  src/components/atoms/Input/Input.tsx
  src/components/molcules/EditProfileImageForm/EditProfileImageForm.tsx
  src/components/molcules/ValidInput/ValidInput.tsx
  src/components/molcules/ValidInput/index.scss
  src/components/molcules/ValidInput/index.ts
  src/components/organisms/EditPassword/EditPassword.tsx
  src/components/organisms/EditPassword/index.ts
  src/components/organisms/EditProfile/EditProfile.tsx
  src/components/templates/EditProfileTemplate/EditProfileTemplate.tsx
  src/components/templates/EditProfileTemplate/index.scss
  src/config/assets.ts
  src/hooks/useEditPassword.ts
  src/services/user/index.ts
Labels: feature, 리뷰 요청

#175 :sparkles: minor layout 조정
  src/components/atoms/Avatar/index.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/index.scss
  src/components/organisms/NavBar/index.scss
  src/styles/layout.scss
Labels: feature, 리뷰 요청

#171 🎉 팔로우 토글 버튼, 팔로워/팔로잉 목록 생성
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/Card/Card.tsx
  src/components/atoms/FollowToggleButton/FollowToggleButton.tsx
  src/components/atoms/FollowToggleButton/index.scss
  src/components/atoms/FollowToggleButton/index.ts
  src/components/molcules/FollowListItem/FollowListItem.tsx
  src/components/molcules/FollowListItem/index.scss
  src/components/organisms/FollowList/FollowList.tsx
  src/components/organisms/FollowList/index.scss
  src/components/organisms/FollowList/index.ts
  src/components/organisms/UserDetailCard/section/Follows.tsx
  src/hooks/useFollow.ts
  src/styles/reset.scss
  src/types/user/index.ts
Labels: feature, 리뷰 요청

#152 🎉 좋아요 싫어요 기능 구현
  src/app/(root)/(routes)/post/[postId]/page.tsx
  src/app/api/likes-cancel/route.ts
  src/app/api/likes/route.ts
  src/app/api/post/[postId]/route.ts
  src/app/api/posts/create/route.ts
  src/components/molcules/LikeDislikeCount/LikeDislikeCount.tsx
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/LikeDisLikeContainer/LikeDIsLikeContainer.tsx
  src/components/organisms/LikeDisLikeContainer/index.scss
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/components/templates/PostDetailTemplate/index.scss
  src/config/environments.ts
  src/constants/post.ts
  src/services/post/like/index.ts
  src/utils/debounce.ts
Labels: feature, 리뷰 요청

#180 🎉 회원가입시 입력받는 username 폼 삭제
  src/components/molcules/SignInput/SignInput.tsx
  src/components/molcules/SignInput/index.scss
  src/components/molcules/SignInput/index.stories.tsx
  src/components/organisms/LogInForm/LoginForm.tsx
  src/components/organisms/SignUpForm/SignUpForm.tsx
  src/components/organisms/SignUpForm/index.scss
Labels: feature, 리뷰 요청

#173 :tada: 유저 카드형 프로필 컴포넌트 구현
  src/components/organisms/CardUserItem/CardUserItem.tsx
  src/components/organisms/CardUserItem/index.scss
  src/components/organisms/CardUserItem/index.stories.ts
  src/components/organisms/CardUserItem/index.ts
Labels: feature, 리뷰 요청

#169 🎉 검색 api 연결 및 post/user 분리 로직 구현
  src/app/(root)/(routes)/search/[keyword]/page.tsx
  src/app/api/search/all/[keyword]/route.ts
  src/services/search/index.ts
Labels: feature, 리뷰 요청

#179 🎉 검색 페이지 구현 완료
  src/app/(root)/(routes)/search/[keyword]/page.tsx
  src/app/api/search/all/[keyword]/route.ts
  src/components/atoms/Card/Card.tsx
  src/components/atoms/SearchBar/SearchBar.tsx
  src/components/organisms/CardUserItem/CardUserItem.tsx
  src/components/organisms/PostGrid/PostGrid.tsx
  src/components/organisms/PostGrid/index.scss
  src/components/organisms/PostGrid/index.ts
  src/components/organisms/UserGrid/UserGrid.tsx
  src/components/organisms/UserGrid/index.scss
  src/components/organisms/UserGrid/index.ts
  src/components/templates/SearchPageTemplate/SearchPageTemplate.tsx
  src/components/templates/SearchPageTemplate/index.scss
  src/components/templates/SearchPageTemplate/index.ts
  src/config/paths.ts
  src/services/search/index.ts
  src/types/user/index.ts
Labels: feature, 리뷰 요청

#176 🎉 내 정보 수정 api 연결
  src/app/(root)/(routes)/user/edit/profile/page.tsx
  src/app/api/users/edit/profile/route.ts
  src/components/molcules/EditNamesForm/EditNamesform.tsx
  src/components/molcules/EditProfileImageForm/EditProfileImageForm.tsx
  src/components/molcules/EditProfileImageForm/index.scss
  src/components/organisms/EditPassword/EditPassword.tsx
  src/components/organisms/EditProfile/EditProfile.tsx
  src/components/organisms/LogInForm/LoginForm.tsx
  src/components/organisms/SignUpForm/SignUpForm.tsx
  src/hooks/useEditPassword.ts
  src/hooks/useEditUserImage.ts
  src/hooks/useEditUserProfile.ts
  src/services/user/edit/password/index.ts
  src/services/user/edit/profile/index.ts
  src/services/user/index.ts
Labels: feature, 리뷰 요청

#190 ✨ 피드백 반영
  src/components/atoms/SearchBar/SearchBar.tsx
  src/components/organisms/PostGrid/PostGrid.tsx
  src/components/templates/SearchPageTemplate/SearchPageTemplate.tsx
  src/components/templates/SearchPageTemplate/index.scss
Labels: feature, 리뷰 요청

#195 🎉 알림 모달창 구현
  src/components/organisms/NotificationModal/NotificationModal.tsx
  src/components/organisms/NotificationModal/index.scss
  src/components/organisms/NotificationModal/index.stories.tsx
  src/components/organisms/NotificationModal/index.ts
  src/constants/notification.ts
  src/types/notification/index.ts
Labels: feature, 리뷰 요청

#185 :tada: html 태그 파싱
  src/app/(root)/(routes)/(home)/page.tsx
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/userPostsGrid/userPostsGrid.tsx
  src/utils/htmlTagParser.ts
Labels: feature, 리뷰 요청

#178 🎉 처음 페이지에서 좋아요 싫어요 개수 반환하게 설정
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/api/posts/route.ts
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/types/post/index.ts
Labels: feature, 리뷰 요청

#199 🎉 비밀번호 검증 모달 구현
  package-lock.json
  src/app/(root)/(routes)/user/edit/profile/page.tsx
  src/components/organisms/PasswordInputModal/PasswordInputModal.tsx
  src/components/organisms/PasswordInputModal/index.ts
  src/hooks/useCheckPassword.ts
Labels: feature, 리뷰 요청

#177 :tada: 사이드바 전체 사용자 목록에 팔로우 기능 추가
  src/components/atoms/Avatar/index.scss
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/FollowToggleButton/FollowToggleButton.tsx
  src/components/atoms/FollowToggleButton/index.scss
  src/components/atoms/Text/Text.tsx
  src/components/molcules/FollowListItem/index.scss
  src/components/molcules/FollowListItem/index.ts
  src/components/organisms/FollowList/index.scss
  src/components/organisms/NavBar/NavBar.tsx
  src/components/organisms/NavBar/index.scss
  src/hooks/useFollow.ts
  src/queries/users/index.ts
  src/types/textStyles/index.ts
  src/types/user/index.ts
Labels: feature, 리뷰 요청

#191 게시글 삭제 기능, 게시글 수정/삭제 옵션 버튼 추가
  public/images/optionsIcon.svg
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/api/post/[postId]/route.ts
  src/components/atoms/Toast/Toast.tsx
  src/components/molcules/FollowListItem/FollowListItem.tsx
  src/components/molcules/ModalDropdownList/index.scss
  src/components/molcules/ModalDropdownList/index.tsx
  src/components/molcules/PostOptionsDropdown/PostOptionsDropdown.tsx
  src/components/molcules/PostOptionsDropdown/index.scss
  src/components/molcules/PostOptionsDropdown/index.ts
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/CardPostItem/index.scss
  src/components/organisms/FollowList/FollowList.tsx
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/components/templates/PostDetailTemplate/index.scss
  src/config/assets.ts
  src/queries/post/index.ts
  src/services/post/index.ts
Labels: feature, 리뷰 요청

#205 🎉 api 연결 구현 완료 및 알림창 연결
  src/app/api/notifications/route.ts
  src/app/api/notifications/seen/route.ts
  src/components/atoms/ImageButton/index.scss
  src/components/atoms/NotificationButton/NotificationButton.tsx
  src/components/organisms/NotificationModal/NotificationModal.tsx
  src/components/organisms/NotificationModal/index.scss
  src/components/organisms/NotificationModal/index.stories.tsx
  src/queries/notifications/index.ts
  src/services/notification/index.ts
Labels: feature, 리뷰 요청

#209 :tada: 알림 컴포넌트 구조 변경
  src/components/atoms/NotificationButton/NotificationButton.tsx
  src/components/organisms/NotificationModal/NotiList.tsx
  src/components/organisms/NotificationModal/NotificationModal.tsx
  src/components/organisms/NotificationModal/index.stories.tsx
  src/queries/notifications/index.ts
Labels: feature

#210 :tada: follow 요청 시 notification 전송
  src/app/api/follow/create/route.ts
Labels: feature

#211 🎉 로그인 회원가입 에러 처리
  src/app/api/login/route.ts
  src/app/api/signup/route.ts
  src/config/paths.ts
  src/constants/sign.ts
  src/hooks/useLogin.ts
  src/hooks/useSignup.ts
  src/lib/axios.ts
Labels: 리뷰 요청

#188 🐛 게시글 검색페이지, 유저 프로필 페이지에서 현재 채널의 상태만 반영
  src/app/api/posts/author/route.ts
  src/app/api/search/all/[keyword]/route.ts
  src/components/organisms/UserDetailCard/UserDetailCard.tsx
  src/components/organisms/userPostsGrid/userPostsGrid.tsx
Labels: 리뷰 요청, bug

#196 :sparkles: 포스트 카드 아이템 스타일, 링크 수정
  src/components/atoms/Text/index.scss
  src/components/organisms/CardPostItem/index.scss
Labels: feature

#193 🎉 댓글 입력 컴포넌트 추가
  src/components/molcules/Comment/Comment.tsx
  src/components/organisms/CommentInput/CommentInput.tsx
  src/components/organisms/CommentInput/index.scss
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
Labels: feature, 리뷰 요청

#198 🎉 게시글 생성 동그란 버튼
  public/images/plusIcon.svg
  src/app/(root)/(routes)/(home)/page.tsx
  src/components/atoms/CirclePlusButton/CirclePlusButton.tsx
  src/components/atoms/CirclePlusButton/index.scss
  src/components/atoms/CirclePlusButton/index.stories.ts
  src/components/atoms/CirclePlusButton/index.ts
  src/config/assets.ts
Labels: feature, 리뷰 요청

#215 🎉 팔로우 버튼 다중클릭시 발생하는 네트워크 오류 해결
  package-lock.json
  src/components/atoms/FollowToggleButton/FollowToggleButton.tsx
Labels: 리뷰 요청, bug

#203 🎉 댓글 API 연결, 댓글 생성시 알림 생성
  src/app/api/cancel-comment/route.ts
  src/app/api/create-comment/notification/route.ts
  src/app/api/create-comment/route.ts
  src/components/molcules/Comment/Comment.tsx
  src/components/molcules/Comment/index.scss
  src/components/organisms/CommentInput/CommentInput.tsx
  src/components/organisms/CommentList/CommentList.tsx
  src/components/organisms/CommentList/CommentListContainer.tsx
  src/components/organisms/CommentList/index.scss
  src/components/organisms/CommentList/index.stories.tsx
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/components/templates/PostDetailTemplate/index.scss
  src/queries/comments/index.ts
  src/services/comment/index.ts
Labels: feature, 리뷰 요청

#214 :sparkles: auth provider 수정
  src/app/(root)/layout.tsx
  src/components/atoms/NotificationButton/NotificationButton.tsx
  src/components/organisms/CommentList/CommentListContainer.tsx
  src/components/organisms/EditProfile/EditProfile.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/PasswordInputModal/PasswordInputModal.tsx
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/components/templates/ModifyPostPageTemplate/ModifyPostPageTemplate.tsx
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/hooks/useCurrentUser.ts
  src/hooks/useFollow.ts
  src/hooks/useLogin.ts
  src/lib/contexts/authProvider.tsx
Labels: feature

#220 Post 카드 레이아웃 조정 및 title 데이터 파싱 처리
  src/app/api/posts/author/route.ts
  src/app/api/search/all/[keyword]/route.ts
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/CardPostItem/index.scss
Labels: 리뷰 요청, bug, refactoring

#238 🎉 댓글 api 알림 부분 수정
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
Labels: feature, 리뷰 요청

#242 🐛 모달 레이아웃 수정
  src/components/molcules/ModalLayout/index.scss
Labels: bug

#233 :tada: 알림 컴포넌트 문제 개선
  src/app/api/create-comment/notification/route.ts
  src/app/api/notifications/seen/route.ts
  src/app/api/users/edit/password/route.ts
  src/components/atoms/NotificationButton/NotificationButton.tsx
  src/components/organisms/NotificationModal/NotiList.tsx
  src/components/organisms/NotificationModal/NotificationModal.tsx
  src/services/notification/index.ts
Labels: 리뷰 요청, bug

#234 :sparkles: 업로드 관련 이슈 수정 및 리팩토링
  package.json
  pnpm-lock.yaml
  src/components/templates/ModifyPostPageTemplate/ModifyPostPageTemplate.tsx
  src/components/templates/ModifyPostPageTemplate/index.scss
  src/components/templates/NewPostPageTemplate/NewPostPageTemplate.tsx
  src/components/templates/NewPostPageTemplate/index.scss
  src/config/postValidation.ts
  src/hooks/useModifyPostForm.ts
  src/hooks/useUploadForm.ts
  src/services/post/index.ts
Labels: feature, 리뷰 요청, bug

#239 :tada: wildcard url 처리
  next.config.js
Labels: 리뷰 요청, bug

#250 🎉 검색 페이지 유저프로필 이동 에러 처리 및 일부 스타일 조정
  src/components/organisms/CardUserItem/CardUserItem.tsx
  src/components/organisms/CardUserItem/index.scss
  src/components/organisms/Header/index.scss
  src/components/organisms/PostGrid/PostGrid.tsx
  src/components/organisms/SearchPostItem/SearchPostItem.tsx
  src/components/organisms/SearchPostItem/index.scss
  src/components/organisms/SearchPostItem/index.ts
Labels: feature, 리뷰 요청, refactoring

#252 ✨ 댓글 입력시 바로 반영되게 설정
  src/components/organisms/CommentInput/CommentInput.tsx
  src/queries/comments/index.ts
Labels: 리뷰 요청, bug

#251 🎉 계정 정보 변경 페이지 ui 변경
  src/components/molcules/EditNamesForm/EditNamesform.tsx
  src/components/molcules/EditProfileImageForm/EditProfileImageForm.tsx
  src/components/molcules/EditProfileImageForm/index.scss
Labels: feature, 리뷰 요청

#248 🐛 팔로우 삭제 -> 신청 -> 삭제 에러 해결
  src/hooks/useFollow.ts
Labels: bug

#245 🎉 아바타 링크 처리
  src/components/organisms/NavBar/NavBar.tsx
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
Labels: feature, 리뷰 요청

#253 🎉 팔로우 리스트 모달 api 호출 지연, 로딩 컴포넌트 추가
  src/components/atoms/Loading/Loading.tsx
  src/components/atoms/Loading/index.scss
  src/components/atoms/Loading/index.stories.ts
  src/components/atoms/Loading/index.ts
  src/components/molcules/FollowListItem/FollowListItem.tsx
  src/components/molcules/FollowListItem/index.scss
  src/components/organisms/UserDetailCard/section/Follows.tsx
Labels: 리뷰 요청, bug, refactoring

#255 :bug: 다크모드 로컬스토리지 -> 쿠키로 수정
  src/app/(root)/layout.tsx
  src/components/atoms/DarkModeButton/index.stories.ts
  src/components/atoms/DarkModeButton/index.tsx
  src/components/molcules/AvatarDropdown/AvatarDropdown.tsx
  src/components/molcules/AvatarDropdown/index.scss
  src/components/molcules/AvatarDropdown/index.ts
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/index.scss
Labels: bug

#228 🐛 글 작성 시 바로 홈 화면에 반영되게 설정
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/api/posts/author/route.ts
  src/app/api/posts/route.ts
  src/components/templates/CardGridTemplate/CardGridTemplate.tsx
  src/queries/channel/index.ts
Labels: 리뷰 요청, bug

#254 🐛 닉네임, 프로필 이미지 변경시 바로 적용
  src/components/molcules/EditNamesForm/EditNamesform.tsx
  src/components/molcules/EditProfileImageForm/EditProfileImageForm.tsx
  src/hooks/useCurrentUser.ts
Labels: 리뷰 요청, bug

#257 :bug: 서버 쿠키 set 제거 (다크모드 client component에서 처리)
  src/components/organisms/Header/Header.tsx
  src/hooks/useDarkmodeCookie.ts
Labels: bug

#244 ✨좋아요 싫어요 바로 반영 안되는 문제
  public/images/activeDisLike.png
  public/images/activeLike.png
  public/images/darkDisLike.png
  public/images/darklike.png
  src/components/molcules/LikeDislikeCount/LikeDislikeCount.tsx
  src/components/organisms/LikeDIsLikeProgressBar/index.tsx
  src/components/organisms/LikeDisLikeContainer/LikeDIsLikeContainer.tsx
  src/components/organisms/LikeDisLikeContainer/index.scss
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/config/assets.ts
  src/stores/darkMode.ts
Labels: 작업 중, bug

#259 :sparkles: header 로딩 방식 수정
  src/app/(root)/layout.tsx
  src/app/api/login/route.ts
  src/components/molcules/AvatarDropdown/AvatarDropdown.tsx
  src/components/organisms/Header/Header.tsx
  src/components/templates/HomePageTemplate/index.tsx
  src/config/environments.ts
  src/hooks/useLogin.ts
  src/hooks/useSignup.ts
  src/lib/contexts/authProvider.tsx
Labels: refactoring

#261 :sparkles: 유저 목록 및 포스트 로딩 방식 수정
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/api/follow/create/route.ts
  src/components/atoms/CirclePlusButton/CirclePlusButton.tsx
  src/components/atoms/ImageButton/imageButton.tsx
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/LogInForm/LoginForm.tsx
  src/components/organisms/NavBar/NavBar.tsx
  src/components/organisms/NavBar/UserList/HydratedUserList.tsx
  src/components/organisms/NavBar/UserList/UserList.tsx
  src/components/templates/CardGridTemplate/GridController.tsx
  src/components/templates/CardGridTemplate/HydrateCardGrid.tsx
  src/lib/queryClient.ts
  src/queries/channel/index.ts
  src/queries/users/index.ts
  src/utils/htmlTagParser.ts
Labels: refactoring

#277 ✨ 드롭다운 스타일 수정, 게시글 수정 페이지 링크 연동
  src/components/molcules/PostOptionsDropdown/PostOptionsDropdown.tsx
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/CardPostItem/index.scss
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/config/paths.ts
Labels: feature, 리뷰 요청

#264 🎉 알림 창 scss 수정
  package-lock.json
  src/components/molcules/AvatarDropdown/index.scss
  src/components/organisms/NotificationModal/NotificationModal.tsx
  src/components/organisms/NotificationModal/index.scss
Labels: feature, 리뷰 요청

#284 :sparkles: 레이아웃 조정
  src/components/atoms/Quill/index.scss
  src/components/templates/ModifyPostPageTemplate/index.scss
  src/components/templates/NewPostPageTemplate/index.scss
  src/components/templates/UserDetailPageTemplate/index.scss
  src/services/post/index.ts
  src/styles/layout.scss
Labels: feature, 리뷰 요청

#279 :bug: 비회원의 경우에 팔로우/팔로잉 숫자 0인 문제 + 팔로우 0일 때도 모달 켜지도록 수정
  src/components/organisms/FollowList/FollowList.tsx
  src/components/organisms/FollowList/index.scss
  src/components/organisms/UserDetailCard/section/Follows.tsx
  src/hooks/useFollow.ts
Labels: 리뷰 요청, bug

#288 :sparkles: 팔로우 리스트 모달 버튼 디자인
  src/components/organisms/UserDetailCard/index.scss
  src/components/organisms/UserDetailCard/section/Follows.tsx
Labels: feature

#289 🎉 댓글 작성,제거시 알림처리
  src/components/organisms/CommentInput/CommentInput.tsx
  src/components/organisms/CommentList/CommentListContainer.tsx
Labels: feature, 리뷰 요청

#286 🐛 비밀번호 검증 모달, 계정 정보 수정 페이지 버그 수정
  package-lock.json
  src/app/(root)/(routes)/user/edit/profile/page.tsx
  src/components/molcules/EditNamesForm/EditNamesform.tsx
  src/components/molcules/EditProfileImageForm/EditProfileImageForm.tsx
  src/components/organisms/EditProfile/EditProfile.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/PasswordInputModal/PasswordInputModal.tsx
Labels: 리뷰 요청, bug

#294 :sparkles: 드랍다운 및 모달 추가 처리
  src/components/atoms/NotificationButton/NotificationButton.tsx
  src/components/atoms/NotificationButton/index.scss
  src/components/atoms/Quill/Quill.tsx
  src/components/molcules/AvatarDropdown/AvatarDropdown.tsx
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/organisms/NotificationModal/NotiList.tsx
  src/components/organisms/NotificationModal/NotificationModal.tsx
  src/components/organisms/NotificationModal/index.scss
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/hooks/useDisLike.ts
  src/hooks/useLike.ts
  src/lib/axios.ts
Labels: feature, 리뷰 요청, refactoring

#303 :tada: favicon 및 타이틀 설정
  public/meta/favicon.ico
  src/app/(root)/layout.tsx
Labels: feature

#300 ✨ 다크모드 스토어 설정 + 따봉이미지 다크모드 일떄 설정
  src/components/atoms/DarkModeButton/index.stories.ts
  src/components/atoms/DarkModeButton/index.tsx
  src/components/molcules/LikeDislikeCount/LikeDislikeCount.tsx
  src/components/organisms/CommentInput/CommentInput.tsx
  src/components/organisms/CommentInput/index.scss
  src/components/organisms/Header/Header.tsx
  src/components/organisms/LikeDisLikeContainer/LikeDIsLikeContainer.tsx
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
  src/hooks/useDarkMode.ts
  src/hooks/useDisLike.ts
  src/hooks/useLike.ts
  src/hooks/useZustandStore.ts
  src/stores/darkMode.ts
Labels: 작업 중, bug

#301 :sparkles: 다크모드 전역 상태 추가 + svg 다크모드용 추가
  public/images/darkDisLike.png
  public/images/darklike.png
  public/images/dislikeWhite.svg
  public/images/likeWhite.svg
  public/images/optionsIconWhite.svg
  src/app/(root)/layout.tsx
  src/components/atoms/DarkModeButton/index.tsx
  src/components/molcules/AvatarDropdown/AvatarDropdown.tsx
  src/components/molcules/LikeDislikeCount/LikeDislikeCount.tsx
  src/components/molcules/PostOptionsDropdown/PostOptionsDropdown.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/LikeDIsLikeProgressBar/index.tsx
  src/components/organisms/LikeDisLikeContainer/LikeDIsLikeContainer.tsx
  src/config/assets.ts
  src/config/constants.ts
  src/hooks/useDarkmodeServerCookie.ts
  src/stores/darkMode.ts
Labels: 리뷰 요청, bug

#305 ✨ 팔로우리스트 리스트 컴포넌트 안에서 로딩 처리
  src/components/atoms/Loading/Loading.tsx
  src/components/atoms/Loading/index.scss
  src/components/atoms/Loading/index.stories.ts
  src/components/organisms/FollowList/FollowList.tsx
  src/components/organisms/UserDetailCard/section/Follows.tsx
Labels: refactoring

#295 :sparkles: Link Prefetch 적용
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/molcules/PostOptionsDropdown/PostOptionsDropdown.tsx
  src/components/organisms/CardPostItem/CardPostItem.tsx
  src/components/organisms/CardUserItem/CardUserItem.tsx
  src/components/organisms/NavBar/UserList/UserList.tsx
  src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
Labels: 리뷰 요청, refactoring

#298 🐛 비밀번호 검증 모달 버그 수정
  src/app/(root)/(routes)/user/edit/profile/page.tsx
  src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
  src/components/organisms/PasswordInputModal/PasswordInputModal.tsx
Labels: 리뷰 요청, bug

#310 :refactor: suspense -> useQuery isLoading으로 변경
  src/components/molcules/FollowListItem/FollowListItem.tsx
  src/components/organisms/FollowList/FollowList.tsx
Labels: refactoring

#311 :tada: 디자인 수정
  src/components/atoms/Avatar/index.scss
  src/components/organisms/CommentInput/index.scss
  src/components/organisms/LikeDisLikeContainer/index.scss
  src/components/templates/PostDetailTemplate/index.scss
  src/hooks/useFollow.ts
Labels: feature, 리뷰 요청, refactoring

#313 :bug: 모달에서 팔로우/팔로우 취소 동작 안되는 문제 해결
  src/hooks/useFollow.ts
Labels: 리뷰 요청, bug
